# the default speed for mouse movement and scrolling
baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

# the time it takes to accelerate to baseMouseSpeed (in ms), 0 to reach top speed immediately
mouseAccelerationTime: 200.0
# the shape of the acceleration curve, 1.0 is linear, higher values have more time at low speeds
mouseAccelerationCurve: 2.0
# speed of the mouse when it starts moving
startMouseSpeed: 0.0
# same for deceleration
mouseDecelerationTime: 300.0
mouseDecelerationCurve: 3.0

layers:
- name: initial
  bindings:
    capslock: tap-hold-next capslock ; toggle-layer mouse ; 500
- name: mouse
  # when true, keys that are not mapped keep their original meaning
  passThrough: true
  bindings:
    r: reload-config
    space: speed 4.0

    h: move -1  0
    j: move  0  1
    k: move  0 -1
    l: move  1  0

    p: scroll up
    n: scroll down

    f: button left
    d: button middle
    s: button right
