#!/usr/bin/env bash

# Script to change alacritty themes.
# Requires:
#   - https://github.com/alacritty/alacritty-theme/
#   - alacritty.yml importing theme.yml

ALACRITTY_DIR=~/.config/alacritty
THEMES_DIR=~/.config/alacritty/themes

if [ -n "$1" ]; then
    # If theme file was given...
    if [ -e $THEMES_DIR/$1 ]; then
        # ...and it exists, then link to it...
        ln -sf $THEMES_DIR/$1 $ALACRITTY_DIR/theme.yml
        # ...and trigger alacritty to reload the config.
        touch $ALACRITTY_DIR/alacritty.yml
    else
        >&2 echo "ERROR: $THEMES_DIR/$1 does not exist"
    fi
else
    # If theme file was not given, show possible ones.
    ls $THEMES_DIR
fi
