#!/usr/bin/env bash

set -x

default_branch=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
current_branch=$(git branch | grep \* | cut -d ' ' -f2)

git checkout "$default_branch"
git fetch --all --prune
git rebase origin/"$default_branch"
git checkout $current_branch
git rebase "$default_branch"
