#!/usr/bin/env bash

usage() {
    echo 'SYNOPSIS'
    echo '    git-fixup TARGET_COMMIT_HASH'
    echo
    echo 'DESCRIPTION'
    echo '    Commits-in staged changes into commit defined by TARGET_COMMIT_HASH'
}

if [ -z "$1" ] || [ $1 == '-h' ] || [ $1 == '--help' ]
    then
        usage
        exit
fi

git commit --fixup="$1"
git rebase -i --autosquash "$1~1"
