#!/usr/bin/env bash

printf "Provide Proton 2FA TOTP code: "
read totp
rclone sync -v --protondrive-2fa="$totp" "$@" ~/wiki proton:wiki
rclone sync -v --protondrive-2fa="$totp" "$@" ~/vault proton:vault
