[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 10.5

[mouse]
hide_when_typing = true

[window]
decorations = "None"
startup_mode = "Maximized"

[colors]
draw_bold_text_with_bright_colors = true
