#!/usr/bin/env python3

import sys
from string import ascii_uppercase

ANSI_NC = "\033[0m"
COLORS = [f"\033[4;{code}m" for code in range(31, 37)]

if len(sys.argv) == 1:
    print(ascii_uppercase)
    sys.exit(0)

letters = set()
for arg in sys.argv[1:]:
    letters.update({letter.upper() for letter in arg})

colored_alphabet = ascii_uppercase
for letter, color in zip(letters, COLORS):
    colored_alphabet = colored_alphabet.replace(letter, f"{color}{letter}{ANSI_NC}")

print(colored_alphabet)
