#!/usr/bin/env python3

import random
import secrets
import string

symbols = ["#", "!", "^"]

# define obligatory symbols in the password
password = []
password.append(secrets.choice(string.ascii_uppercase))
password.append(secrets.choice(symbols))
password.append(secrets.choice(string.digits))

# define charset for additional characters
charset = [
    *string.ascii_lowercase,
    *string.ascii_uppercase,
    *symbols,
]

# choose additional characters and shuffle whole password
for _ in range(29):
    password.append(secrets.choice(charset))

random.shuffle(password)

# don't allow special characters at the beginning of the pswd
while password[0] in symbols:
    random.shuffle(password)

print("".join(password))
