colors:
  body: none
  date: GREEN
  tags: BLUE
  title: YELLOW
default_hour: 9
default_minute: 0
editor: 'vim'
encrypt: false
highlight: true
indent_character: '│'
journals:
  default: $HOME/journals/default.txt
  todo: $HOME/journals/todo.txt
linewrap: 80
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v2.8.4
